package com.czl.chatClient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "IM_TABLE".
 */
public class Pushmessage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String alert;
	private String channelid;
	private String dataid;
	private String detail;
	private String fromid;
	private String fromlogourl;
	private String fromname;
	private String sendtime;
	private String toid;
	private String type;
	private String title;
	private int status;
	private boolean isNewMsg = true;
	private String uid;
	private String picUrl;
	private String voicestream;

	public Pushmessage() {
	}

	public Pushmessage(String channelid, String alert, String dataid, String detail, String fromid,
			String fromlogourl, String fromname, String sendtime, String toid, String type, String title, String uid,
			Integer status, Boolean isNewMsg) {
		this.channelid = channelid;
		this.alert = alert;
		this.dataid = dataid;
		this.detail = detail;
		this.fromid = fromid;
		this.fromlogourl = fromlogourl;
		this.fromname = fromname;
		this.sendtime = sendtime;
		this.toid = toid;
		this.type = type;
		this.title = title;
		this.uid = uid;
		this.status = status;
		this.isNewMsg = isNewMsg;
	}

	public String getChannelid() {
		return channelid;
	}

	public void setChannelid(String channelid) {
		this.channelid = channelid;
	}

	public String getAlert() {
		return alert;
	}

	public void setAlert(String alert) {
		this.alert = alert;
	}

	public String getDataid() {
		return dataid;
	}

	public void setDataid(String dataid) {
		this.dataid = dataid;
	}

	public String getDetail() {
		return detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public String getFromid() {
		return fromid;
	}

	public void setFromid(String fromid) {
		this.fromid = fromid;
	}

	public String getFromlogourl() {
		return fromlogourl;
	}

	public void setFromlogourl(String fromlogourl) {
		this.fromlogourl = fromlogourl;
	}

	public String getFromname() {
		return fromname;
	}

	public void setFromname(String fromname) {
		this.fromname = fromname;
	}

	public String getSendtime() {
		return sendtime;
	}

	public void setSendtime(String sendtime) {
		this.sendtime = sendtime;
	}

	public String getToid() {
		return toid;
	}

	public void setToid(String toid) {
		this.toid = toid;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Boolean getIsNewMsg() {
		return isNewMsg;
	}

	public void setIsNewMsg(Boolean isNewMsg) {
		this.isNewMsg = isNewMsg;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public boolean isNewMsg() {
		return isNewMsg;
	}

	public void setNewMsg(boolean newMsg) {
		isNewMsg = newMsg;
	}

	public String getPicUrl() {
		return picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	public String getVoicestream() {
		return voicestream;
	}

	public void setVoicestream(String voicestream) {
		this.voicestream = voicestream;
	}

	@Override
	public String toString() {
		return "Pushmessage{" +
				"alert='" + alert + '\'' +
				", channelid='" + channelid + '\'' +
				", dataid='" + dataid + '\'' +
				", detail='" + detail + '\'' +
				", fromid='" + fromid + '\'' +
				", fromlogourl='" + fromlogourl + '\'' +
				", fromname='" + fromname + '\'' +
				", sendtime='" + sendtime + '\'' +
				", toid='" + toid + '\'' +
				", type='" + type + '\'' +
				", title='" + title + '\'' +
				", status=" + status +
				", isNewMsg=" + isNewMsg +
				", uid='" + uid + '\'' +
				", picUrl='" + picUrl + '\'' +
				", voicestream='" + voicestream + '\'' +
				'}';
	}
}
